version: "3"
services:
  # vpn:
  #   image: azinchen/nordvpn:latest
  #   cap_add:
  #     - net_admin
  #   devices:
  #     - /dev/net/tun
  #   environment:
  #     - USER=${VPNMAIL}
  #     - PASS=${VPNPASSWORD}
  #     - COUNTRY=Germany;Switzerland
  #     - CATEGORY=P2P
  #     - RANDOM_TOP=10
  #     - RECREATE_VPN_CRON=5 */3 * * *
  #     - NETWORK=192.168.1.0/24;192.168.2.0/24
  #     - OPENVPN_OPTS=--mute-replay-warnings
  #   ports:
  #     - 8080:80
  #     - 8090:8090
  #     - 25565:25565
  #     - 9229:9229
  #   restart: unless-stopped

  twoboardtwowait:
    build: 
      context: '.'
    volumes:
      - 'nmp-cache:/srv/app/nmp-cache'
      - 'config-file:/srv/app/config'
    ports:
      - 8090:8090
      - 25565:25565
    # network_mode: service:vpn
    # depends_on:
    #   - vpn
    restart: "always"
volumes:
  nmp-cache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: './nmp-cache'
  config-file:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: './config'